* build the wts-build project by running ant
	* this build procedure results in a jar wts-build.jar
	* put this jar together with jdom.jar in the CLASSPATH
		* eg. export CLASSPATH=.:/home/plibin0/tmp/wts-build/dist/wts-build.jar:/home/plibin0/tmp/wts-build/lib/jdom.jar
* build the wts project by running ant 